services:
  api:
    build: 
      context: ..
      dockerfile: docker/node.Dockerfile
      target: api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/flowforge
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
      KMS_KEY: dev_only_32bytes_key_dev_only_
      WEBHOOK_SALT: devsalt
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: ["pnpm","--filter","@flowforge/api","dev"]
    volumes:
      - ..:/repo
  worker:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
      target: worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/flowforge
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KMS_KEY: dev_only_32bytes_key_dev_only_
    depends_on:
      - db
      - redis
    command: ["pnpm","--filter","@flowforge/worker","dev"]
    ports: []
    volumes:
      - ..:/repo
  web:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
      target: web
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: ["pnpm","--filter","@flowforge/web","dev","--","--host","0.0.0.0"]
    environment:
      VITE_API_BASE: http://api:3000
    volumes:
      - ..:/repo
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
volumes:
  pgdata:
  minio:
